### Listar productos
GET http://localhost:3000/producto

### Crear producto
POST http://localhost:3000/producto
Content-Conent-Type: application/json
{
    "nombre":"teclado",
    "precio": "500.95",
    "stock":12,
    "categoriaId":1
}

### Busqueda por nombre
GET http://localhost:300/producto/back?page=3